imsmcf:
    hostname: hostname
    datastorename: IMSA
    portnumber: 9999
    sslenabled: false
    username: userid
    password: password
    connectionpoolenabled: true
    minconnections: 3
    maxconnections: 10    